on: push

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5433:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

      minio:
        # fixme: let's not depend on external unofficial image
        image: lazybit/minio
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: root
          MINIO_ROOT_PASSWORD: active_storage_test
        options: --name=minio --health-cmd "curl http://localhost:9000/minio/health/live"


    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
      REDIS_URL: redis://localhost:6379/0
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: mfinelli/setup-imagemagick@v1
      - name: Install Ubuntu dependencies
        run: sudo apt-get -y install poppler-data poppler-utils ffmpeg mupdf-tools
      - name: Check identify
        run: identify --version

      - run: wget https://dl.min.io/client/mc/release/linux-amd64/mc
      - run: chmod +x ./mc
      - run: ./mc alias set minio http://127.0.0.1:9000 root active_storage_test
      - run: ./mc mb --ignore-existing minio/active_storage_test

      - uses: erlef/setup-beam@v1
        with:
          otp-version: '24'
          elixir-version: '1.12'
      - run: mix deps.get
      - run: mix test.all